# Tomcat 定义
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms

spring:
  # 项目名称
  application:
    name: stock_backend
  # 配置mysql数据源
  datasource:
    druid:
      username: root
      password: 806823
      url: jdbc:mysql://127.0.0.1:3306/stock_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 6
      # 最小连接池数量
      minIdle: 2
      # 最大连接池数量
      maxActive: 20
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的 sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      validationQuery: SELECT 1 FROM DUAL
      # 建议配置为 true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      # 归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false
      # 是否自动回收超时连接
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 配置 Redis
  redis:
    host: 124.220.194.38
    password: 806823
    port: 6379
    database: 0 #Redis数据库索引（默认为0）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1  # 连接池中的最小空闲连接
    timeout: PT10S # 连接超时时间（毫秒）

# 配置 mybatis
mybatis:
  type-aliases-package: com.lt.stock.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启控制台打印 SQL
    map-underscore-to-camel-case: true # 开启驼峰命名
    cache-enabled: false #使全局的映射器启用或禁用缓存。
    lazy-loading-enabled: false #全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载。
    aggressive-lazy-loading: true #当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。

# pageHelper 配置
pagehelper:
  helper-dialect: mysql # 指定分页数据库，不指定的话会默认自动检测数据库类型
  reasonable: true # 是否启用分页合理化，当 pagenum< 1 显示第一页，当 pagenum > pages 显示最后一页
  support-methods-arguments: true # 支持通过Mapper接口参数来传递分页参数，默认false
  params: pacount=countSql # POJO或者Map中发现了countSql属性，就会作为count参数使用
  returnPageInfo: check # always总是返回PageInfo类型,check检查返回类型是否为PageInfo,none返回Page

# XXJOB参数配置
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8082/xxl-job-admin
    executor:
      appname: stock-xxl-job-executor
      address:
      ip:
      port: 6666
      logpath: /joblog
      logretentiondays: 30

# 配置httpClient请求参数
http:
  pool:
    # 整个线程池中最大连接数（整个线程池中最大连接数）
    maxConnectionTotal: 50
    # 路由到某台主机最大并发数
    routeMaxCount: 20
    # 连接空闲超时，清楚闲置的连接
    connectionIdleTimeOut: 5000
    # 重试次数，防止失败情况
    retryCount: 2
    # 客户端和服务器建立连接的超时时间
    connectionTimeOut: 5000
    # 客户端从服务器读取数据的超时时间
    readTimeOut: 7000
    # 从连接池中获取连接的超时时间
    connectionRequestTimeOut: 5000
    # 连接保持存活时间
    defaultKeepAliveTimeMillis: 20000

# 定时任务线程池基础参数
task:
  pool:
    corePoolSize: 5 # 核心线程数
    maxPoolSize: 21 # 设置最大线程数
    keepAliveSeconds: 300 # 设置线程活跃时间
    queueCapacity: 100 # 设置队列容量

# 配置股票相关的参数
stock:
  inner: # A股
    - s_sh000001 # 上证ID
    - s_sz399001 # 深证ID
  outer: # 外盘
    - int_dji # 道琼斯
    - int_nasdaq # 纳斯达克
    - int_hangseng # 恒生
    - int_nikkei # 日经指数
    - b_TWSE # 台湾加权
    - b_FSSTI # 新加坡
  upDownRange: # 涨幅范围集合
    - "<-7%"
    - "-7~-5%"
    - "-5~-3%"
    - "-3~0%"
    - "0~3%"
    - "3~5%"
    - "5~7%"
    - ">7%"
  marketUrl: http://hq.sinajs.cn/list= # 大盘 股票数据接口
  blockUrl: http://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php # 板块数据接口
